sudo:
  - required
services:
  - docker
install: skip

script:
  - sh "tests/${TEST_INSTANCE}.sh"

env:
  - TEST_INSTANCE=test-alpine
  - TEST_INSTANCE=test-debian
  - TEST_INSTANCE=test-ubuntu
  - TEST_INSTANCE=test-centos
  - TEST_INSTANCE=test-arch
  - TEST_INSTANCE=test-fedora
  - TEST_INSTANCE=test-opensuse
  - TEST_INSTANCE=coverage
